import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunitoSerif = Nunito({
    variable: "--font-nunito-serif",
    subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-b from-transparent via-transparent to-pink-900/20 ${nunitoSerif.variable} font-serif w-screen h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
